# docker-compose.yaml
version: "3.7"
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: ["nodemon", "."]
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./web
        target: /home/node/web
  db:
    image: postgres
    restart: always